<?php
/**
 * BankInformationModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

/**
 * BankInformationModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BankInformationModelAttributes
{
    public string $strBankAccountNumber = 'bank_account_number';
    public string $strBankGiroNumber = 'bank_giro_number';
    public string $strBankName = 'bank_name';
    public string $strBankSortCode = 'bank_sort_code';
    public string $strPbcCustomerGroupNumber = 'pbc_customer_group_number';
    public string $strPbsFiSupplierNumber = 'pbs_fi_supplier_number';
}

