<?php
/**
 * CompanyModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

/**
 * CompanyModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompanyModelAttributes
{
    public string $strAddressLine1 = 'address_line1';
    public string $strAddressLine2 = 'address_line2';
    public string $strAttention = 'attention';
    public string $strCity = 'city';
    public string $strCompanyIdentificationNumber = 'company_identification_number';
    public string $strCountry = 'country';
    public string $strEmail = 'email';
    public string $strName = 'name';
    public string $strPhoneNumber = 'phone_number';
    public string $strVatNumber = 'vat_number';
    public string $strWebSite = 'web_site';
    public string $strZip = 'zip';
}

