<?php
/**
 * EntryModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

/**
 * EntryModelAttributes Class Doc Comment
 *
 * @category Class
 * @description A specific entry in the accounting year.
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EntryModelAttributes
{
    public string $strAccount = 'account';
    public string $strAmount = 'amount';
    public string $strSupplierInvoiceNumber = 'supplier_invoice_number';
    public string $strAmountInBaseCurrency = 'amount_in_base_currency';
    public string $strCurrency = 'currency';
    public string $strDate = 'date';
    public string $strDueDate = 'due_date';
    public string $strDepartmentalDistribution = 'departmental_distribution';
    public string $strProject = 'project';
    public string $strCostType = 'cost_type';
    public string $strEntryNumber = 'entry_number';
    public string $strText = 'text';
    public string $strEntryType = 'entry_type';
    public string $strVatAccount = 'vat_account';
    public string $strCustomer = 'customer';
    public string $strSupplier = 'supplier';
    public string $strUnit1 = 'unit1';
    public string $strUnit2 = 'unit2';
    public string $strQuantity1 = 'quantity1';
    public string $strQuantity2 = 'quantity2';
    public string $strVoucherNumber = 'voucher_number';
    public string $strBookedInvoice = 'booked_invoice';
    public string $strInvoiceNumber = 'invoice_number';
    public string $strRemainder = 'remainder';
    public string $strRemainderInBaseCurrency = 'remainder_in_base_currency';
    public string $strPaymentDetails = 'payment_details';
    public string $strSelf = 'self';
}

