<?php
/**
 * JournalModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

/**
 * JournalModelFields Class Doc Comment
 *
 * @category Class
 * @description A schema for fetching specific journal.
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JournalModelFields
{
    public string $strName = 'name';
    public string $strSettings = 'settings';
    public string $strVouchers = 'vouchers';
    public string $strEntries = 'entries';
    public string $strTemplates = 'templates';
    public string $strJournalNumber = 'journalNumber';
    public string $strSelf = 'self';
}

