<?php
/**
 * JournalSettings
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

use \ArrayAccess;
use \EconomicRest\ObjectSerializer;

/**
 * JournalSettings Class Doc Comment
 *
 * @category Class
 * @description Settings of the journal.
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class JournalSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return JournalSettingsModelFields
      */
    public static function GetModelFields(): JournalSettingsModelFields
    {
        return new JournalSettingsModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return JournalSettingsModelAttributes
      */
    public static function GetModelAttributes(): JournalSettingsModelAttributes
    {
        return new JournalSettingsModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JournalSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'voucher_numbers' => '\EconomicRest\Model\JournalVoucherNumbers',
        'entry_type_restricted_to' => 'string',
        'contra_accounts' => '\EconomicRest\Model\JournalContraAccounts'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'voucher_numbers' => null,
        'entry_type_restricted_to' => null,
        'contra_accounts' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'voucher_numbers' => false,
        'entry_type_restricted_to' => false,
        'contra_accounts' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'voucher_numbers' => 'voucherNumbers',
        'entry_type_restricted_to' => 'entryTypeRestrictedTo',
        'contra_accounts' => 'contraAccounts'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'voucher_numbers' => 'setVoucherNumbers',
        'entry_type_restricted_to' => 'setEntryTypeRestrictedTo',
        'contra_accounts' => 'setContraAccounts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'voucher_numbers' => 'getVoucherNumbers',
        'entry_type_restricted_to' => 'getEntryTypeRestrictedTo',
        'contra_accounts' => 'getContraAccounts'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ENTRY_TYPE_RESTRICTED_TO_FINANCE_VOUCHER = 'financeVoucher';
    public const ENTRY_TYPE_RESTRICTED_TO_SUPPLIER_INVOICE = 'supplierInvoice';
    public const ENTRY_TYPE_RESTRICTED_TO_SUPPLIER_PAYMENT = 'supplierPayment';
    public const ENTRY_TYPE_RESTRICTED_TO_CUSTOMER_PAYMENT = 'customerPayment';
    public const ENTRY_TYPE_RESTRICTED_TO_MANUAL_CUSTOMER_INVOICE = 'manualCustomerInvoice';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEntryTypeRestrictedToAllowableValues()
    {
        return [
            self::ENTRY_TYPE_RESTRICTED_TO_FINANCE_VOUCHER,
            self::ENTRY_TYPE_RESTRICTED_TO_SUPPLIER_INVOICE,
            self::ENTRY_TYPE_RESTRICTED_TO_SUPPLIER_PAYMENT,
            self::ENTRY_TYPE_RESTRICTED_TO_CUSTOMER_PAYMENT,
            self::ENTRY_TYPE_RESTRICTED_TO_MANUAL_CUSTOMER_INVOICE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('voucher_numbers', $data ?? [], null);
        $this->setIfExists('entry_type_restricted_to', $data ?? [], null);
        $this->setIfExists('contra_accounts', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getEntryTypeRestrictedToAllowableValues();
        if (!is_null($this->container['entry_type_restricted_to']) && !in_array($this->container['entry_type_restricted_to'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'entry_type_restricted_to', must be one of '%s'",
                $this->container['entry_type_restricted_to'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets voucher_numbers
     *
     * @return \EconomicRest\Model\JournalVoucherNumbers|null
     */
    public function getVoucherNumbers()
    {
        return $this->container['voucher_numbers'];
    }

    /**
     * Sets voucher_numbers
     *
     * @param \EconomicRest\Model\JournalVoucherNumbers|null $voucher_numbers voucher_numbers
     *
     * @return self
     */
    public function setVoucherNumbers($voucher_numbers)
    {
        if (is_null($voucher_numbers)) {
            throw new \InvalidArgumentException('non-nullable voucher_numbers cannot be null');
        }
        $this->container['voucher_numbers'] = $voucher_numbers;

        return $this;
    }

    /**
     * Gets entry_type_restricted_to
     *
     * @return string|null
     */
    public function getEntryTypeRestrictedTo()
    {
        return $this->container['entry_type_restricted_to'];
    }

    /**
     * Sets entry_type_restricted_to
     *
     * @param string|null $entry_type_restricted_to Allowed entry type on given journal.
     *
     * @return self
     */
    public function setEntryTypeRestrictedTo($entry_type_restricted_to)
    {
        if (is_null($entry_type_restricted_to)) {
            throw new \InvalidArgumentException('non-nullable entry_type_restricted_to cannot be null');
        }
        $allowedValues = $this->getEntryTypeRestrictedToAllowableValues();
        if (!in_array($entry_type_restricted_to, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'entry_type_restricted_to', must be one of '%s'",
                    $entry_type_restricted_to,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['entry_type_restricted_to'] = $entry_type_restricted_to;

        return $this;
    }

    /**
     * Gets contra_accounts
     *
     * @return \EconomicRest\Model\JournalContraAccounts|null
     */
    public function getContraAccounts()
    {
        return $this->container['contra_accounts'];
    }

    /**
     * Sets contra_accounts
     *
     * @param \EconomicRest\Model\JournalContraAccounts|null $contra_accounts contra_accounts
     *
     * @return self
     */
    public function setContraAccounts($contra_accounts)
    {
        if (is_null($contra_accounts)) {
            throw new \InvalidArgumentException('non-nullable contra_accounts cannot be null');
        }
        $this->container['contra_accounts'] = $contra_accounts;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


