<?php
/**
 * JournalTemplatesModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

/**
 * JournalTemplatesModelAttributes Class Doc Comment
 *
 * @category Class
 * @description Templates allowing easy entry creation.
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JournalTemplatesModelAttributes
{
    public string $strFinanceVoucher = 'finance_voucher';
    public string $strManualCustomerInvoice = 'manual_customer_invoice';
    public string $strSelf = 'self';
}

