<?php
/**
 * ManualCustomerInvoiceEntryModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

/**
 * ManualCustomerInvoiceEntryModelAttributes Class Doc Comment
 *
 * @category Class
 * @description Manual Customer Invoice entry.
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ManualCustomerInvoiceEntryModelAttributes
{
    public string $strText = 'text';
    public string $strJournal = 'journal';
    public string $strAmount = 'amount';
    public string $strContraAccount = 'contra_account';
    public string $strContraVatAccount = 'contra_vat_account';
    public string $strCurrency = 'currency';
    public string $strDate = 'date';
    public string $strDepartmentalDistribution = 'departmental_distribution';
    public string $strExchangeRate = 'exchange_rate';
    public string $strEntryType = 'entry_type';
    public string $strVoucher = 'voucher';
    public string $strContraVatAmount = 'contra_vat_amount';
    public string $strContraVatAmountInBaseCurrency = 'contra_vat_amount_in_base_currency';
    public string $strAmountBaseCurrency = 'amount_base_currency';
    public string $strRemainder = 'remainder';
    public string $strRemainderInDefaultCurrency = 'remainder_in_default_currency';
    public string $strCustomer = 'customer';
    public string $strCustomerInvoice = 'customer_invoice';
    public string $strDueDate = 'due_date';
}

