<?php
/**
 * PaginationModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

/**
 * PaginationModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaginationModelAttributes
{
    public string $strMaxPageSizeAllowed = 'max_page_size_allowed';
    public string $strSkipPages = 'skip_pages';
    public string $strPageSize = 'page_size';
    public string $strResults = 'results';
    public string $strResultsWithoutFilter = 'results_without_filter';
    public string $strFirstPage = 'first_page';
    public string $strNextPage = 'next_page';
    public string $strLastPage = 'last_page';
    public string $strDeveloperHint = 'developer_hint';
}

