<?php
/**
 * PaginationModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EconomicRest\Model;

/**
 * PaginationModelFields Class Doc Comment
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaginationModelFields
{
    public string $strMaxPageSizeAllowed = 'maxPageSizeAllowed';
    public string $strSkipPages = 'skipPages';
    public string $strPageSize = 'pageSize';
    public string $strResults = 'results';
    public string $strResultsWithoutFilter = 'resultsWithoutFilter';
    public string $strFirstPage = 'firstPage';
    public string $strNextPage = 'nextPage';
    public string $strLastPage = 'lastPage';
    public string $strDeveloperHint = 'developerHint';
}

