<?php
/**
 * JournalEntryTemplateHandlerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EconomicRest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * e-conomic JSON-schema REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EconomicRest\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * JournalEntryTemplateHandlerTest Class Doc Comment
 *
 * @category    Class
 * @description Templates allowing easy entry creation, its existance depends on the type of the entry.
 * @package     EconomicRest
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class JournalEntryTemplateHandlerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "JournalEntryTemplateHandler"
     */
    public function testJournalEntryTemplateHandler()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_payment"
     */
    public function testPropertyCustomerPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contra_account"
     */
    public function testPropertyContraAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_and_contra_account"
     */
    public function testPropertyAccountAndContraAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
